// Generated by CoffeeScript 1.7.1
(function() {
  var keyList, video, videoElement, videoList;

  videoElement = $('#video');

  video = videoElement[0];

  videoList = ["assets/videos/xx_1.mp4", "assets/videos/xx_2.mp4", "assets/videos/xx_3.mp4"];

  keyList = [49, 50, 51];

  $(document).ready(function() {
    video.onended = function() {
      return video.src = '';
    };
    return $(document).keypress(function(e) {
      console.log(e.keyCode);
      switch (e.keyCode) {
        case 102:
          if (screenfull.enabled) {
            return screenfull.request(video);
          }
          break;
        case 112:
          return video.pause();
        case keyList[0]:
          video.src = videoList[0];
          return video.play();
        case keyList[1]:
          video.src = videoList[1];
          return video.play();
        case keyList[2]:
          video.src = videoList[2];
          return video.play();
      }
    });
  });

}).call(this);
